<?xml version="1.0" encoding = "Windows-1252"?>
<VisualStudioProject
	ProjectType="Visual C++"
	Version="9.00"
	Name="ALL_BUILD"
	SccProjectName=""
	SccLocalPath=""
	Keyword="Win32Proj">
	<Platforms>
		<Platform
			Name="Win32"/>
	</Platforms>
	<Configurations>
		<Configuration
			Name="Debug|Win32"
			OutputDirectory="Debug"
			IntermediateDirectory="ALL_BUILD.dir\Debug"
			ConfigurationType="10"
			UseOfMFC="0"
			ATLMinimizesCRunTimeLibraryUsage="FALSE"
			CharacterSet="2">
			<Tool
				Name="VCCLCompilerTool"
				AdditionalIncludeDirectories="C:\Stuff\gg\Source\Utilities\OSG_SVN\Visual_Studio_9_2008_Win32\include;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\include;"
				ExceptionHandling="FALSE"
				PreprocessorDefinitions="_SCL_SECURE_NO_WARNINGS,_CRT_SECURE_NO_DEPRECATE,&quot;OSG_DEBUG_POSTFIX=d&quot;,&quot;CMAKE_INTDIR=\&quot;Debug\&quot;&quot;"
				AssemblerListingLocation="Debug"
				ObjectFile="$(IntDir)\"
/>
			<Tool
				Name="VCCustomBuildTool"/>
			<Tool
				Name="VCResourceCompilerTool"
				AdditionalIncludeDirectories="C:\Stuff\gg\Source\Utilities\OSG_SVN\Visual_Studio_9_2008_Win32\include;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\include;"
				PreprocessorDefinitions="_SCL_SECURE_NO_WARNINGS,_CRT_SECURE_NO_DEPRECATE,&quot;OSG_DEBUG_POSTFIX=d&quot;,&quot;CMAKE_INTDIR=\&quot;Debug\&quot;&quot;"/>
			<Tool
				Name="VCMIDLTool"
				PreprocessorDefinitions="_SCL_SECURE_NO_WARNINGS,_CRT_SECURE_NO_DEPRECATE,&quot;OSG_DEBUG_POSTFIX=d&quot;,&quot;CMAKE_INTDIR=\&quot;Debug\&quot;&quot;"
				MkTypLibCompatible="FALSE"
				TargetEnvironment="1"
				GenerateStublessProxies="TRUE"
				TypeLibraryName="$(InputName).tlb"
				OutputDirectory="$(IntDir)"
				HeaderFileName="$(InputName).h"
				DLLDataFileName=""
				InterfaceIdentifierFileName="$(InputName)_i.c"
				ProxyFileName="$(InputName)_p.c"/>
			<Tool
				Name="VCPreBuildEventTool"/>
			<Tool
				Name="VCPreLinkEventTool"/>
			<Tool
				Name="VCPostBuildEventTool"/>
		</Configuration>
		<Configuration
			Name="Release|Win32"
			OutputDirectory="Release"
			IntermediateDirectory="ALL_BUILD.dir\Release"
			ConfigurationType="10"
			UseOfMFC="0"
			ATLMinimizesCRunTimeLibraryUsage="FALSE"
			CharacterSet="2">
			<Tool
				Name="VCCLCompilerTool"
				AdditionalIncludeDirectories="C:\Stuff\gg\Source\Utilities\OSG_SVN\Visual_Studio_9_2008_Win32\include;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\include;"
				ExceptionHandling="FALSE"
				PreprocessorDefinitions="_SCL_SECURE_NO_WARNINGS,_CRT_SECURE_NO_DEPRECATE,&quot;OSG_DEBUG_POSTFIX=d&quot;,&quot;CMAKE_INTDIR=\&quot;Release\&quot;&quot;"
				AssemblerListingLocation="Release"
				ObjectFile="$(IntDir)\"
/>
			<Tool
				Name="VCCustomBuildTool"/>
			<Tool
				Name="VCResourceCompilerTool"
				AdditionalIncludeDirectories="C:\Stuff\gg\Source\Utilities\OSG_SVN\Visual_Studio_9_2008_Win32\include;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\include;"
				PreprocessorDefinitions="_SCL_SECURE_NO_WARNINGS,_CRT_SECURE_NO_DEPRECATE,&quot;OSG_DEBUG_POSTFIX=d&quot;,&quot;CMAKE_INTDIR=\&quot;Release\&quot;&quot;"/>
			<Tool
				Name="VCMIDLTool"
				PreprocessorDefinitions="_SCL_SECURE_NO_WARNINGS,_CRT_SECURE_NO_DEPRECATE,&quot;OSG_DEBUG_POSTFIX=d&quot;,&quot;CMAKE_INTDIR=\&quot;Release\&quot;&quot;"
				MkTypLibCompatible="FALSE"
				TargetEnvironment="1"
				GenerateStublessProxies="TRUE"
				TypeLibraryName="$(InputName).tlb"
				OutputDirectory="$(IntDir)"
				HeaderFileName="$(InputName).h"
				DLLDataFileName=""
				InterfaceIdentifierFileName="$(InputName)_i.c"
				ProxyFileName="$(InputName)_p.c"/>
			<Tool
				Name="VCPreBuildEventTool"/>
			<Tool
				Name="VCPreLinkEventTool"/>
			<Tool
				Name="VCPostBuildEventTool"/>
		</Configuration>
	</Configurations>
	<Files>
			<File
				RelativePath="C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\CMakeLists.txt">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCustomBuildTool"
					Description="Building Custom Rule C:/Stuff/gg/Source/Utilities/OSG_SVN/OpenSceneGraph/CMakeLists.txt"
					CommandLine="&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\bin\cmake.exe&quot; -HC:/Stuff/gg/Source/Utilities/OSG_SVN/OpenSceneGraph -BC:/Stuff/gg/Source/Utilities/OSG_SVN/Visual_Studio_9_2008_Win32"
					AdditionalDependencies="C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\CMakeLists.txt;C:\Stuff\gg\Source\Utilities\OSG_SVN\Visual_Studio_9_2008_Win32\CMakeFiles\CMakeSystem.cmake;C:\Stuff\gg\Source\Utilities\OSG_SVN\Visual_Studio_9_2008_Win32\CMakeFiles\CMakeCCompiler.cmake;C:\Stuff\gg\Source\Utilities\OSG_SVN\Visual_Studio_9_2008_Win32\CMakeFiles\CMakeCXXCompiler.cmake;&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\share\cmake-2.4\Modules\CMakeSystemSpecificInformation.cmake&quot;;&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\share\cmake-2.4\Modules\CMakeGenericSystem.cmake&quot;;&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\share\cmake-2.4\Modules\Platform\gcc.cmake&quot;;&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\share\cmake-2.4\Modules\Platform\Windows.cmake&quot;;&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\share\cmake-2.4\Modules\Platform\WindowsPaths.cmake&quot;;&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\share\cmake-2.4\Modules\CMakeCInformation.cmake&quot;;&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\share\cmake-2.4\Modules\Platform\Windows-cl.cmake&quot;;C:\Stuff\gg\Source\Utilities\OSG_SVN\Visual_Studio_9_2008_Win32\CMakeFiles\CMakeCPlatform.cmake;C:\Stuff\gg\Source\Utilities\OSG_SVN\Visual_Studio_9_2008_Win32\CMakeFiles\CMakeCXXPlatform.cmake;C:\Stuff\gg\Source\Utilities\OSG_SVN\Visual_Studio_9_2008_Win32\CMakeFiles\CMakeRCCompiler.cmake;&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\share\cmake-2.4\Modules\CMakeRCInformation.cmake&quot;;&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\share\cmake-2.4\Modules\CMakeCommonLanguageInclude.cmake&quot;;&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\share\cmake-2.4\Modules\CMakeCXXInformation.cmake&quot;;&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\share\cmake-2.4\Modules\Platform\Windows-cl.cmake&quot;;C:\Stuff\gg\Source\Utilities\OSG_SVN\Visual_Studio_9_2008_Win32\CMakeFiles\CMakeCPlatform.cmake;C:\Stuff\gg\Source\Utilities\OSG_SVN\Visual_Studio_9_2008_Win32\CMakeFiles\CMakeCXXPlatform.cmake;&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\share\cmake-2.4\Modules\CMakeCommonLanguageInclude.cmake&quot;;&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\share\cmake-2.4\Modules\FindThreads.cmake&quot;;&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\share\cmake-2.4\Modules\CheckIncludeFile.cmake&quot;;&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\share\cmake-2.4\Modules\CheckIncludeFiles.cmake&quot;;&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\share\cmake-2.4\Modules\CheckLibraryExists.cmake&quot;;&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\share\cmake-2.4\Modules\FindOpenGL.cmake&quot;;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\src\osg\Config.in;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\PlatformSpecifics\Windows\OpenSceneGraphVersionInfo.rc.in;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\CMakeModules\Find3rdPartyDependencies.cmake;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\CMakeModules\FindFreeType.cmake;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\CMakeModules\FindInventor.cmake;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\CMakeModules\FindJasper.cmake;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\CMakeModules\FindOpenEXR.cmake;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\CMakeModules\FindCOLLADA.cmake;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\CMakeModules\FindZLIB.cmake;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\CMakeModules\FindXine.cmake;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\CMakeModules\FindOpenVRML.cmake;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\CMakeModules\FindPerformer.cmake;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\CMakeModules\FindGDAL.cmake;&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\share\cmake-2.4\Modules\FindCURL.cmake&quot;;&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\share\cmake-2.4\Modules\FindITK.cmake&quot;;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\CMakeModules\FindLibVNCServer.cmake;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\CMakeModules\FindOurDCMTK.cmake;&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\share\cmake-2.4\Modules\FindOpenAL.cmake&quot;;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\CMakeModules\FindXUL.cmake;&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\share\cmake-2.4\Modules\FindPkgConfig.cmake&quot;;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\CMakeModules\FindFFmpeg.cmake;&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\share\cmake-2.4\Modules\FindSDL.cmake&quot;;&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\share\cmake-2.4\Modules\FindThreads.cmake&quot;;&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\share\cmake-2.4\Modules\CheckIncludeFile.cmake&quot;;&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\share\cmake-2.4\Modules\CheckIncludeFiles.cmake&quot;;&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\share\cmake-2.4\Modules\CheckLibraryExists.cmake&quot;;&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\share\cmake-2.4\Modules\FindPkgConfig.cmake&quot;;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\CMakeModules\FindGIFLIB.cmake;&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\share\cmake-2.4\Modules\FindJPEG.cmake&quot;;&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\share\cmake-2.4\Modules\FindPNG.cmake&quot;;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\CMakeModules\FindZLIB.cmake;&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\share\cmake-2.4\Modules\FindTIFF.cmake&quot;;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\CMakeModules\FindQuickTime.cmake;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\CMakeModules\OsgMacroUtils.cmake;&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\share\cmake-2.4\Modules\Documentation.cmake&quot;;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\packaging\pkgconfig\openscenegraph.pc.in;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\packaging\pkgconfig\openscenegraph-osg.pc.in;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\packaging\pkgconfig\openscenegraph-osgDB.pc.in;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\packaging\pkgconfig\openscenegraph-osgFX.pc.in;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\packaging\pkgconfig\openscenegraph-osgGA.pc.in;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\packaging\pkgconfig\openscenegraph-osgParticle.pc.in;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\packaging\pkgconfig\openscenegraph-osgSim.pc.in;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\packaging\pkgconfig\openscenegraph-osgText.pc.in;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\packaging\pkgconfig\openscenegraph-osgUtil.pc.in;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\packaging\pkgconfig\openscenegraph-osgTerrain.pc.in;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\packaging\pkgconfig\openscenegraph-osgManipulator.pc.in;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\packaging\pkgconfig\openscenegraph-osgViewer.pc.in;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\packaging\pkgconfig\openscenegraph-osgWidget.pc.in;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\packaging\pkgconfig\openscenegraph-osgShadow.pc.in;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\packaging\pkgconfig\openscenegraph-osgAnimation.pc.in;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\packaging\pkgconfig\openscenegraph-osgVolume.pc.in;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\packaging\pkgconfig\openscenegraph-osgIntrospection.pc.in;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\CMakeModules\cmake_uninstall.cmake.in;&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\share\cmake-2.4\Templates\CMakeWindowsSystemConfig.cmake&quot;;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\CMakeLists.txt;"
					Outputs="wrappers.vcproj.cmake"/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCustomBuildTool"
					Description="Building Custom Rule C:/Stuff/gg/Source/Utilities/OSG_SVN/OpenSceneGraph/CMakeLists.txt"
					CommandLine="&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\bin\cmake.exe&quot; -HC:/Stuff/gg/Source/Utilities/OSG_SVN/OpenSceneGraph -BC:/Stuff/gg/Source/Utilities/OSG_SVN/Visual_Studio_9_2008_Win32"
					AdditionalDependencies="C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\CMakeLists.txt;C:\Stuff\gg\Source\Utilities\OSG_SVN\Visual_Studio_9_2008_Win32\CMakeFiles\CMakeSystem.cmake;C:\Stuff\gg\Source\Utilities\OSG_SVN\Visual_Studio_9_2008_Win32\CMakeFiles\CMakeCCompiler.cmake;C:\Stuff\gg\Source\Utilities\OSG_SVN\Visual_Studio_9_2008_Win32\CMakeFiles\CMakeCXXCompiler.cmake;&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\share\cmake-2.4\Modules\CMakeSystemSpecificInformation.cmake&quot;;&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\share\cmake-2.4\Modules\CMakeGenericSystem.cmake&quot;;&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\share\cmake-2.4\Modules\Platform\gcc.cmake&quot;;&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\share\cmake-2.4\Modules\Platform\Windows.cmake&quot;;&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\share\cmake-2.4\Modules\Platform\WindowsPaths.cmake&quot;;&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\share\cmake-2.4\Modules\CMakeCInformation.cmake&quot;;&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\share\cmake-2.4\Modules\Platform\Windows-cl.cmake&quot;;C:\Stuff\gg\Source\Utilities\OSG_SVN\Visual_Studio_9_2008_Win32\CMakeFiles\CMakeCPlatform.cmake;C:\Stuff\gg\Source\Utilities\OSG_SVN\Visual_Studio_9_2008_Win32\CMakeFiles\CMakeCXXPlatform.cmake;C:\Stuff\gg\Source\Utilities\OSG_SVN\Visual_Studio_9_2008_Win32\CMakeFiles\CMakeRCCompiler.cmake;&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\share\cmake-2.4\Modules\CMakeRCInformation.cmake&quot;;&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\share\cmake-2.4\Modules\CMakeCommonLanguageInclude.cmake&quot;;&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\share\cmake-2.4\Modules\CMakeCXXInformation.cmake&quot;;&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\share\cmake-2.4\Modules\Platform\Windows-cl.cmake&quot;;C:\Stuff\gg\Source\Utilities\OSG_SVN\Visual_Studio_9_2008_Win32\CMakeFiles\CMakeCPlatform.cmake;C:\Stuff\gg\Source\Utilities\OSG_SVN\Visual_Studio_9_2008_Win32\CMakeFiles\CMakeCXXPlatform.cmake;&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\share\cmake-2.4\Modules\CMakeCommonLanguageInclude.cmake&quot;;&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\share\cmake-2.4\Modules\FindThreads.cmake&quot;;&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\share\cmake-2.4\Modules\CheckIncludeFile.cmake&quot;;&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\share\cmake-2.4\Modules\CheckIncludeFiles.cmake&quot;;&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\share\cmake-2.4\Modules\CheckLibraryExists.cmake&quot;;&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\share\cmake-2.4\Modules\FindOpenGL.cmake&quot;;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\src\osg\Config.in;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\PlatformSpecifics\Windows\OpenSceneGraphVersionInfo.rc.in;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\CMakeModules\Find3rdPartyDependencies.cmake;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\CMakeModules\FindFreeType.cmake;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\CMakeModules\FindInventor.cmake;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\CMakeModules\FindJasper.cmake;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\CMakeModules\FindOpenEXR.cmake;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\CMakeModules\FindCOLLADA.cmake;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\CMakeModules\FindZLIB.cmake;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\CMakeModules\FindXine.cmake;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\CMakeModules\FindOpenVRML.cmake;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\CMakeModules\FindPerformer.cmake;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\CMakeModules\FindGDAL.cmake;&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\share\cmake-2.4\Modules\FindCURL.cmake&quot;;&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\share\cmake-2.4\Modules\FindITK.cmake&quot;;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\CMakeModules\FindLibVNCServer.cmake;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\CMakeModules\FindOurDCMTK.cmake;&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\share\cmake-2.4\Modules\FindOpenAL.cmake&quot;;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\CMakeModules\FindXUL.cmake;&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\share\cmake-2.4\Modules\FindPkgConfig.cmake&quot;;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\CMakeModules\FindFFmpeg.cmake;&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\share\cmake-2.4\Modules\FindSDL.cmake&quot;;&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\share\cmake-2.4\Modules\FindThreads.cmake&quot;;&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\share\cmake-2.4\Modules\CheckIncludeFile.cmake&quot;;&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\share\cmake-2.4\Modules\CheckIncludeFiles.cmake&quot;;&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\share\cmake-2.4\Modules\CheckLibraryExists.cmake&quot;;&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\share\cmake-2.4\Modules\FindPkgConfig.cmake&quot;;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\CMakeModules\FindGIFLIB.cmake;&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\share\cmake-2.4\Modules\FindJPEG.cmake&quot;;&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\share\cmake-2.4\Modules\FindPNG.cmake&quot;;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\CMakeModules\FindZLIB.cmake;&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\share\cmake-2.4\Modules\FindTIFF.cmake&quot;;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\CMakeModules\FindQuickTime.cmake;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\CMakeModules\OsgMacroUtils.cmake;&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\share\cmake-2.4\Modules\Documentation.cmake&quot;;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\packaging\pkgconfig\openscenegraph.pc.in;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\packaging\pkgconfig\openscenegraph-osg.pc.in;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\packaging\pkgconfig\openscenegraph-osgDB.pc.in;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\packaging\pkgconfig\openscenegraph-osgFX.pc.in;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\packaging\pkgconfig\openscenegraph-osgGA.pc.in;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\packaging\pkgconfig\openscenegraph-osgParticle.pc.in;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\packaging\pkgconfig\openscenegraph-osgSim.pc.in;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\packaging\pkgconfig\openscenegraph-osgText.pc.in;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\packaging\pkgconfig\openscenegraph-osgUtil.pc.in;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\packaging\pkgconfig\openscenegraph-osgTerrain.pc.in;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\packaging\pkgconfig\openscenegraph-osgManipulator.pc.in;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\packaging\pkgconfig\openscenegraph-osgViewer.pc.in;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\packaging\pkgconfig\openscenegraph-osgWidget.pc.in;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\packaging\pkgconfig\openscenegraph-osgShadow.pc.in;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\packaging\pkgconfig\openscenegraph-osgAnimation.pc.in;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\packaging\pkgconfig\openscenegraph-osgVolume.pc.in;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\packaging\pkgconfig\openscenegraph-osgIntrospection.pc.in;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\CMakeModules\cmake_uninstall.cmake.in;&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\share\cmake-2.4\Templates\CMakeWindowsSystemConfig.cmake&quot;;C:\Stuff\gg\Source\Utilities\OSG_SVN\OpenSceneGraph\CMakeLists.txt;"
					Outputs="wrappers.vcproj.cmake"/>
				</FileConfiguration>
			</File>
		<Filter
			Name="CMake Rules"
			Filter="">
			<File
				RelativePath="C:\Stuff\gg\Source\Utilities\OSG_SVN\Visual_Studio_9_2008_Win32\CMakeFiles\ALL_BUILD.rule">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCustomBuildTool"
					Description=""
					CommandLine="echo &quot;Build all projects&quot;"
					AdditionalDependencies="C:\Stuff\gg\Source\Utilities\OSG_SVN\Visual_Studio_9_2008_Win32\CMakeFiles\ALL_BUILD.rule"
					Outputs="C:\Stuff\gg\Source\Utilities\OSG_SVN\Visual_Studio_9_2008_Win32\CMakeFiles\ALL_BUILD"/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCustomBuildTool"
					Description=""
					CommandLine="echo &quot;Build all projects&quot;"
					AdditionalDependencies="C:\Stuff\gg\Source\Utilities\OSG_SVN\Visual_Studio_9_2008_Win32\CMakeFiles\ALL_BUILD.rule"
					Outputs="C:\Stuff\gg\Source\Utilities\OSG_SVN\Visual_Studio_9_2008_Win32\CMakeFiles\ALL_BUILD"/>
				</FileConfiguration>
			</File>
		</Filter>
	</Files>
	<Globals>
	</Globals>
</VisualStudioProject>
