include $(DWMAKE)/makedefs
TOPDIR=./

CXXFILES = main.cpp\
		   expcow.cpp\
		   Explosion.cpp\

LIBS = -losgParticle -losgText -losgUtil -losgGA -losgDB -losgProducer -losg -lProducer -lOpenThreads
EXEC  = exp

COMPILER_INCLUDE += -I/usr/X11R6/include

include $(DWMAKE)/makerules
