TOPDIR = ../../
include $(TOPDIR)/Make/makedefs
include $(TOPDIR)/Test/Make/localdefs

CXXFILES = \
    main.cpp\

LIBS = \
	-losgProducer -losgDB -losgGA -losgText -losgUtil -losg \
	-lProducer -lOpenThreads

EXEC = trackball_test

include $(TOPDIR)/Make/makerules
