TOPDIR = ../../
include $(TOPDIR)/Make/makedefs
include $(TOPDIR)/Test/Make/localdefs

CXXFILES = \
    main.cpp\

LIBS = -lProducer -lOpenThreads

EXEC = version_test

include $(TOPDIR)/Make/makerules
