TOPDIR = ../../
include $(TOPDIR)/Make/makedefs
include $(TOPDIR)/Test/Make/localdefs

CXXFILES = \
    main.cpp\
    Text.cpp\

LIBS = -lProducer $(GL_LIBS) -lOpenThreads


EXEC = rendersurface_test

include $(TOPDIR)/Make/makerules
