xcopy .\Content-Source .\HIGH_RES /S /Y /E /I /Exclude:Exclude_Raw.txt 

convert ".\Content-Source\Fighter_Colonial_Q33\BAKE_engine.PNG" -resize 256 ".\HIGH_RES\Fighter_Colonial_Q33\BAKE_engine.PNG"
convert ".\Content-Source\Fighter_Colonial_Q33\BAKE-Q33-Hull02.PNG" -resize 512 ".\HIGH_RES\Fighter_Colonial_Q33\BAKE-Q33-Hull02.PNG"
convert ".\Content-Source\Fighter_Colonial_Q33\BAKE-Q-33-Gun01.PNG" -resize 256 ".\HIGH_RES\Fighter_Colonial_Q33\BAKE-Q-33-Gun01.PNG"
convert ".\Content-Source\Fighter_Colonial_Q33\Q33-A Cockpit-02.PNG" -resize 256 ".\HIGH_RES\Fighter_Colonial_Q33\Q33-A Cockpit-02.PNG"
convert ".\Content-Source\Fighter_Colonial_Q33\Q33-A Cockpit-TRANS-Invert.PNG" -resize 256 ".\HIGH_RES\Fighter_Colonial_Q33\Q33-A Cockpit-TRANS-Invert.PNG"
convert ".\Content-Source\Fighter_Colonial_Q33\TransFade-01.PNG" -resize 256 ".\HIGH_RES\Fighter_Colonial_Q33\TransFade-01.PNG"
convert ".\Content-Source\Fighter_Colonial_Q33\grievousutapau1.PNG" -resize 128 ".\HIGH_RES\Fighter_Colonial_Q33\grievousutapau1.PNG"

convert ".\Content-Source\Polygon FX\CornerGlow.PNG" -resize 64 ".\HIGH_RES\Polygon FX\CornerGlow.PNG"
convert ".\Content-Source\Polygon FX\EngineGlowCorner-Alpha.PNG" -resize 128 ".\HIGH_RES\Polygon FX\EngineGlowCorner-Alpha.PNG"
convert ".\Content-Source\Polygon FX\EngineGlowCorner-blue.PNG" -resize 128 ".\HIGH_RES\Polygon FX\EngineGlowCorner-blue.PNG"
convert ".\Content-Source\Polygon FX\LadingLight-01.PNG" -resize 128 ".\HIGH_RES\Polygon FX\LadingLight-01.PNG"
convert ".\Content-Source\Polygon FX\MGunPloom-01-512.PNG" -resize 128 ".\HIGH_RES\Polygon FX\MGunPloom-01-512.PNG"
convert ".\Content-Source\Polygon FX\TransFade-01.PNG" -resize 128 ".\HIGH_RES\Polygon FX\TransFade-01.PNG"
convert ".\Content-Source\Polygon FX\TrustGlow-01-BLUE.PNG" -resize 128 ".\HIGH_RES\Polygon FX\TrustGlow-01-BLUE.PNG"
convert ".\Content-Source\Polygon FX\TrustGlow-01-GOLD.PNG" -resize 128 ".\HIGH_RES\Polygon FX\TrustGlow-01-GOLD.PNG"
convert ".\Content-Source\Polygon FX\TrustGlow-01-GREEN.PNG" -resize 128 ".\HIGH_RES\Polygon FX\TrustGlow-01-GREEN.PNG"
convert ".\Content-Source\Polygon FX\TrustGlow-01-RED.PNG" -resize 128 ".\HIGH_RES\Polygon FX\TrustGlow-01-RED.PNG"
convert ".\Content-Source\Polygon FX\TrustGlow-01-TEAL.PNG" -resize 128 ".\HIGH_RES\Polygon FX\TrustGlow-01-TEAL.PNG"
convert ".\Content-Source\Polygon FX\TrustGlow-01-THRUSTHAZE.PNG" -resize 256 ".\HIGH_RES\Polygon FX\TrustGlow-01-THRUSTHAZE.PNG"
convert ".\Content-Source\Polygon FX\TrustGlow-01-TRANS.PNG" -resize 128 ".\HIGH_RES\Polygon FX\TrustGlow-01-TRANS.PNG"

convert ".\Content-Source\POSER_Union_Orion\BAKE Bridge.PNG" -resize 512 ".\HIGH_RES\POSER_Union_Orion\BAKE Bridge.PNG"
convert ".\Content-Source\POSER_Union_Orion\BAKE Central Hull-01 Underhull.PNG" -resize 512 ".\HIGH_RES\POSER_Union_Orion\BAKE Central Hull-01 Underhull.PNG"
convert ".\Content-Source\POSER_Union_Orion\BAKE Central Hull-02 Hull.PNG" -resize 512 ".\HIGH_RES\POSER_Union_Orion\BAKE Central Hull-02 Hull.PNG"
convert ".\Content-Source\POSER_Union_Orion\BAKE Central Hull-02 Underhull.PNG" -resize 512 ".\HIGH_RES\POSER_Union_Orion\BAKE Central Hull-02 Underhull.PNG"
convert ".\Content-Source\POSER_Union_Orion\BAKE Central Hull-03 Hull.PNG" -resize 512 ".\HIGH_RES\POSER_Union_Orion\BAKE Central Hull-03 Hull.PNG"
convert ".\Content-Source\POSER_Union_Orion\BAKE Central Hull 01.PNG" -resize 512 ".\HIGH_RES\POSER_Union_Orion\BAKE Central Hull 01.PNG"
convert ".\Content-Source\POSER_Union_Orion\BAKE Collector Hull.PNG" -resize 512 ".\HIGH_RES\POSER_Union_Orion\BAKE Collector Hull.PNG"
convert ".\Content-Source\POSER_Union_Orion\BAKE Collector Hull Dark.PNG" -resize 512 ".\HIGH_RES\POSER_Union_Orion\BAKE Collector Hull Dark.PNG"
convert ".\Content-Source\POSER_Union_Orion\BAKE Cowling.PNG" -resize 512 ".\HIGH_RES\POSER_Union_Orion\BAKE Cowling.PNG"
convert ".\Content-Source\POSER_Union_Orion\BAKE Engine Hull.PNG" -resize 512 ".\HIGH_RES\POSER_Union_Orion\BAKE Engine Hull.PNG"
convert ".\Content-Source\POSER_Union_Orion\BAKE TurretMount.PNG" -resize 256 ".\HIGH_RES\POSER_Union_Orion\BAKE TurretMount.PNG"
convert ".\Content-Source\POSER_Union_Orion\BAKED Underhull.PNG" -resize 512 ".\HIGH_RES\POSER_Union_Orion\BAKED Underhull.PNG"
convert ".\Content-Source\POSER_Union_Orion\Engine Flame Alpha.PNG" -resize 256 ".\HIGH_RES\POSER_Union_Orion\Engine Flame Alpha.PNG"
convert ".\Content-Source\POSER_Union_Orion\Engine Flame Color.PNG" -resize 256 ".\HIGH_RES\POSER_Union_Orion\Engine Flame Color.PNG"
convert ".\Content-Source\POSER_Union_Orion\Engineglow.PNG" -resize 128 ".\HIGH_RES\POSER_Union_Orion\Engineglow.PNG"
convert ".\Content-Source\POSER_Union_Orion\Engines.PNG" -resize 512 ".\HIGH_RES\POSER_Union_Orion\Engines.PNG"
convert ".\Content-Source\POSER_Union_Orion\Specular Panels 01.PNG" -resize 512 ".\HIGH_RES\POSER_Union_Orion\Specular Panels 01.PNG"
convert ".\Content-Source\POSER_Union_Orion\Specular Panels 02.PNG" -resize 512 ".\HIGH_RES\POSER_Union_Orion\Specular Panels 02.PNG"

convert ".\Content-Source\Fighter_Union_Vexhall\BAKED_Bottom.PNG" -resize 512 ".\HIGH_RES\Fighter_Union_Vexhall\BAKED_Bottom.PNG"
convert ".\Content-Source\Fighter_Union_Vexhall\BAKED_top.PNG" -resize 512 ".\HIGH_RES\Fighter_Union_Vexhall\BAKED_top.PNG"
convert ".\Content-Source\Fighter_Union_Vexhall\BAKED_Details.PNG" -resize 512 ".\HIGH_RES\Fighter_Union_Vexhall\BAKED_Details.PNG"

convert ".\Content-Source\POSER_Frigate_Union_Karackuss\BAKE_Karackuss_details.PNG" -resize 1024 ".\HIGH_RES\POSER_Frigate_Union_Karackuss\BAKE_Karackuss_details.PNG"
convert ".\Content-Source\POSER_Frigate_Union_Karackuss\BAKE_Karackuss_HULL.PNG" -resize 1024 ".\HIGH_RES\POSER_Frigate_Union_Karackuss\BAKE_Karackuss_HULL.PNG"
convert ".\Content-Source\POSER_Frigate_Union_Karackuss\QuadPanels.PNG" -resize 512 ".\HIGH_RES\POSER_Frigate_Union_Karackuss\QuadPanels.PNG"
convert ".\Content-Source\POSER_Frigate_Union_Karackuss\BAKE-MedRail-01.PNG" -resize 512 ".\HIGH_RES\POSER_Frigate_Union_Karackuss\BAKE-MedRail-01.PNG"

convert ".\Content-Source\Space_Ring01\ring_01.PNG" -resize 512 ".\HIGH_RES\Space_Ring01\ring_01.PNG"