TOPDIR = ../../
include $(TOPDIR)/Make/makedefs
include $(TOPDIR)/Test/Make/localdefs

CXXFILES = \
        main.cpp\
        glut_teapot.cpp

LIBS = -lProducer 

EXEC = twoCameras

include $(TOPDIR)/Make/makerules
