<?xml version="1.0" encoding = "Windows-1252"?>
<VisualStudioProject
	ProjectType="Visual C++"
	Version="9.00"
	Name="osgWidget"
	SccProjectName=""
	SccLocalPath=""
	Keyword="Win32Proj">
	<Platforms>
		<Platform
			Name="Win32"/>
	</Platforms>
	<Configurations>
		<Configuration
			Name="Debug|Win32"
			OutputDirectory="Debug"
			IntermediateDirectory="osgWidget.dir\Debug"
			ConfigurationType="2"
			UseOfMFC="0"
			ATLMinimizesCRunTimeLibraryUsage="FALSE"
			CharacterSet="2">
			<Tool
				Name="VCCLCompilerTool"
				AdditionalOptions=" /Zm1000"
				AdditionalIncludeDirectories="$(GG_UTILITIES)\OSG_SVN\OSG_10297_VS_2008\include;$(GG_UTILITIES)\OSG_SVN\OpenSceneGraph\include;"
				BasicRuntimeChecks="1"
				CompileAs="2"
				DebugInformationFormat="3"
				ExceptionHandling="1"
				InlineFunctionExpansion="0"
				Optimization="0"
				RuntimeLibrary="3"
				RuntimeTypeInfo="TRUE"
				WarningLevel="3"
				PreprocessorDefinitions="WIN32,_WINDOWS,_DEBUG,_SCL_SECURE_NO_WARNINGS,_CRT_SECURE_NO_DEPRECATE,&quot;OSG_DEBUG_POSTFIX=d&quot;,OSGWIDGET_LIBRARY,&quot;CMAKE_INTDIR=\&quot;Debug\&quot;&quot;,osgWidget_EXPORTS"
				AssemblerListingLocation="Debug"
				ObjectFile="$(IntDir)\"
				ProgramDataBaseFileName="$(GG_UTILITIES)/OSG_SVN/OSG_10297_VS_2008/lib/Debug/osgWidgetd.pdb"
/>
			<Tool
				Name="VCCustomBuildTool"/>
			<Tool
				Name="VCResourceCompilerTool"
				AdditionalIncludeDirectories="$(GG_UTILITIES)\OSG_SVN\OSG_10297_VS_2008\include;$(GG_UTILITIES)\OSG_SVN\OpenSceneGraph\include;"
				PreprocessorDefinitions="WIN32,_WINDOWS,_DEBUG,_SCL_SECURE_NO_WARNINGS,_CRT_SECURE_NO_DEPRECATE,&quot;OSG_DEBUG_POSTFIX=d&quot;,OSGWIDGET_LIBRARY,&quot;CMAKE_INTDIR=\&quot;Debug\&quot;&quot;,osgWidget_EXPORTS"/>
			<Tool
				Name="VCMIDLTool"
				PreprocessorDefinitions="WIN32,_WINDOWS,_DEBUG,_SCL_SECURE_NO_WARNINGS,_CRT_SECURE_NO_DEPRECATE,&quot;OSG_DEBUG_POSTFIX=d&quot;,OSGWIDGET_LIBRARY,&quot;CMAKE_INTDIR=\&quot;Debug\&quot;&quot;,osgWidget_EXPORTS"
				MkTypLibCompatible="FALSE"
				TargetEnvironment="1"
				GenerateStublessProxies="TRUE"
				TypeLibraryName="$(InputName).tlb"
				OutputDirectory="$(IntDir)"
				HeaderFileName="$(InputName).h"
				DLLDataFileName=""
				InterfaceIdentifierFileName="$(InputName)_i.c"
				ProxyFileName="$(InputName)_p.c"/>
			<Tool
				Name="VCPreBuildEventTool"/>
			<Tool
				Name="VCPreLinkEventTool"/>
			<Tool
				Name="VCPostBuildEventTool"/>
			<Tool
				Name="VCLinkerTool"
				AdditionalOptions=" /STACK:10000000 /machine:I386 /debug"
				AdditionalDependencies="$(NOINHERIT) kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib osgTextd.lib osgViewerd.lib osgDBd.lib osgd.lib OpenThreadsd.lib osgGAd.lib glu32.lib opengl32.lib osgTextd.lib osgDBd.lib glu32.lib opengl32.lib osgUtild.lib osgd.lib OpenThreadsd.lib "
				OutputFile="$(GG_UTILITIES)\OSG_SVN\OSG_10297_VS_2008\lib\Debug\osgWidgetd.dll"
				Version="2.9"
				LinkIncremental="2"
				AdditionalLibraryDirectories="..\..\lib\$(OutDir),..\..\lib"
				ProgramDataBaseFile="$(GG_UTILITIES)\OSG_SVN\OSG_10297_VS_2008\lib\$(OutDir)\osgWidgetd.pdb"
				GenerateDebugInformation="TRUE"
				ImportLibrary="$(GG_UTILITIES)\OSG_SVN\OSG_10297_VS_2008\lib\Debug\osgWidgetd.lib"/>
		</Configuration>
		<Configuration
			Name="Release|Win32"
			OutputDirectory="Release"
			IntermediateDirectory="osgWidget.dir\Release"
			ConfigurationType="2"
			UseOfMFC="0"
			ATLMinimizesCRunTimeLibraryUsage="FALSE"
			CharacterSet="2">
			<Tool
				Name="VCCLCompilerTool"
				AdditionalOptions=" /Zm1000"
				AdditionalIncludeDirectories="$(GG_UTILITIES)\OSG_SVN\OSG_10297_VS_2008\include;$(GG_UTILITIES)\OSG_SVN\OpenSceneGraph\include;"
				CompileAs="2"
				ExceptionHandling="1"
				InlineFunctionExpansion="2"
				Optimization="2"
				RuntimeLibrary="2"
				RuntimeTypeInfo="TRUE"
				WarningLevel="3"
				PreprocessorDefinitions="WIN32,_WINDOWS,NDEBUG,_SCL_SECURE_NO_WARNINGS,_CRT_SECURE_NO_DEPRECATE,&quot;OSG_DEBUG_POSTFIX=d&quot;,OSGWIDGET_LIBRARY,&quot;CMAKE_INTDIR=\&quot;Release\&quot;&quot;,osgWidget_EXPORTS"
				AssemblerListingLocation="Release"
				ObjectFile="$(IntDir)\"
				ProgramDataBaseFileName="$(GG_UTILITIES)/OSG_SVN/OSG_10297_VS_2008/lib/Release/osgWidget.pdb"
/>
			<Tool
				Name="VCCustomBuildTool"/>
			<Tool
				Name="VCResourceCompilerTool"
				AdditionalIncludeDirectories="$(GG_UTILITIES)\OSG_SVN\OSG_10297_VS_2008\include;$(GG_UTILITIES)\OSG_SVN\OpenSceneGraph\include;"
				PreprocessorDefinitions="WIN32,_WINDOWS,NDEBUG,_SCL_SECURE_NO_WARNINGS,_CRT_SECURE_NO_DEPRECATE,&quot;OSG_DEBUG_POSTFIX=d&quot;,OSGWIDGET_LIBRARY,&quot;CMAKE_INTDIR=\&quot;Release\&quot;&quot;,osgWidget_EXPORTS"/>
			<Tool
				Name="VCMIDLTool"
				PreprocessorDefinitions="WIN32,_WINDOWS,NDEBUG,_SCL_SECURE_NO_WARNINGS,_CRT_SECURE_NO_DEPRECATE,&quot;OSG_DEBUG_POSTFIX=d&quot;,OSGWIDGET_LIBRARY,&quot;CMAKE_INTDIR=\&quot;Release\&quot;&quot;,osgWidget_EXPORTS"
				MkTypLibCompatible="FALSE"
				TargetEnvironment="1"
				GenerateStublessProxies="TRUE"
				TypeLibraryName="$(InputName).tlb"
				OutputDirectory="$(IntDir)"
				HeaderFileName="$(InputName).h"
				DLLDataFileName=""
				InterfaceIdentifierFileName="$(InputName)_i.c"
				ProxyFileName="$(InputName)_p.c"/>
			<Tool
				Name="VCPreBuildEventTool"/>
			<Tool
				Name="VCPreLinkEventTool"/>
			<Tool
				Name="VCPostBuildEventTool"/>
			<Tool
				Name="VCLinkerTool"
				AdditionalOptions=" /STACK:10000000 /machine:I386"
				AdditionalDependencies="$(NOINHERIT) kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib osgText.lib osgViewer.lib osgDB.lib osg.lib OpenThreads.lib osgGA.lib glu32.lib opengl32.lib osgText.lib osgDB.lib osgUtil.lib glu32.lib opengl32.lib osg.lib OpenThreads.lib "
				OutputFile="$(GG_UTILITIES)\OSG_SVN\OSG_10297_VS_2008\lib\Release\osgWidget.dll"
				Version="2.9"
				LinkIncremental="1"
				AdditionalLibraryDirectories="..\..\lib\$(OutDir),..\..\lib"
				ProgramDataBaseFile="$(GG_UTILITIES)\OSG_SVN\OSG_10297_VS_2008\lib\$(OutDir)\osgWidget.pdb"
				ImportLibrary="$(GG_UTILITIES)\OSG_SVN\OSG_10297_VS_2008\lib\Release\osgWidget.lib"/>
		</Configuration>
	</Configurations>
	<Files>
			<File
				RelativePath="$(GG_UTILITIES)\OSG_SVN\OpenSceneGraph\src\osgWidget\CMakeLists.txt">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCustomBuildTool"
					Description="Building Custom Rule $(GG_UTILITIES)/OSG_SVN/OpenSceneGraph/src/osgWidget/CMakeLists.txt"
					CommandLine="&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\bin\cmake.exe&quot; -H$(GG_UTILITIES)/OSG_SVN/OpenSceneGraph -B$(GG_UTILITIES)/OSG_SVN/OSG_10297_VS_2008"
					AdditionalDependencies="$(GG_UTILITIES)\OSG_SVN\OpenSceneGraph\src\osgWidget\CMakeLists.txt;$(GG_UTILITIES)\OSG_SVN\OpenSceneGraph\CMakeModules\ModuleInstall.cmake;&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\share\cmake-2.4\Templates\CMakeWindowsSystemConfig.cmake&quot;;$(GG_UTILITIES)\OSG_SVN\OpenSceneGraph\src\osgWidget\CMakeLists.txt;"
					Outputs="osgWidget.vcproj.cmake"/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCustomBuildTool"
					Description="Building Custom Rule $(GG_UTILITIES)/OSG_SVN/OpenSceneGraph/src/osgWidget/CMakeLists.txt"
					CommandLine="&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\bin\cmake.exe&quot; -H$(GG_UTILITIES)/OSG_SVN/OpenSceneGraph -B$(GG_UTILITIES)/OSG_SVN/OSG_10297_VS_2008"
					AdditionalDependencies="$(GG_UTILITIES)\OSG_SVN\OpenSceneGraph\src\osgWidget\CMakeLists.txt;$(GG_UTILITIES)\OSG_SVN\OpenSceneGraph\CMakeModules\ModuleInstall.cmake;&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\share\cmake-2.4\Templates\CMakeWindowsSystemConfig.cmake&quot;;$(GG_UTILITIES)\OSG_SVN\OpenSceneGraph\src\osgWidget\CMakeLists.txt;"
					Outputs="osgWidget.vcproj.cmake"/>
				</FileConfiguration>
			</File>
			<File
				RelativePath="$(GG_UTILITIES)\OSG_SVN\OpenSceneGraph\src\osgWidget\CMakeLists.txt">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCustomBuildTool"
					Description="Building Custom Rule $(GG_UTILITIES)/OSG_SVN/OpenSceneGraph/src/osgWidget/CMakeLists.txt"
					CommandLine="&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\bin\cmake.exe&quot; -H$(GG_UTILITIES)/OSG_SVN/OpenSceneGraph -B$(GG_UTILITIES)/OSG_SVN/OSG_10297_VS_2008"
					AdditionalDependencies="$(GG_UTILITIES)\OSG_SVN\OpenSceneGraph\src\osgWidget\CMakeLists.txt;$(GG_UTILITIES)\OSG_SVN\OpenSceneGraph\CMakeModules\ModuleInstall.cmake;&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\share\cmake-2.4\Templates\CMakeWindowsSystemConfig.cmake&quot;;$(GG_UTILITIES)\OSG_SVN\OpenSceneGraph\src\osgWidget\CMakeLists.txt;"
					Outputs="osgWidget.vcproj.cmake"/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCustomBuildTool"
					Description="Building Custom Rule $(GG_UTILITIES)/OSG_SVN/OpenSceneGraph/src/osgWidget/CMakeLists.txt"
					CommandLine="&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\bin\cmake.exe&quot; -H$(GG_UTILITIES)/OSG_SVN/OpenSceneGraph -B$(GG_UTILITIES)/OSG_SVN/OSG_10297_VS_2008"
					AdditionalDependencies="$(GG_UTILITIES)\OSG_SVN\OpenSceneGraph\src\osgWidget\CMakeLists.txt;$(GG_UTILITIES)\OSG_SVN\OpenSceneGraph\CMakeModules\ModuleInstall.cmake;&quot;C:\Program Files (x86)\cmake-2.4.8-win32-x86\share\cmake-2.4\Templates\CMakeWindowsSystemConfig.cmake&quot;;$(GG_UTILITIES)\OSG_SVN\OpenSceneGraph\src\osgWidget\CMakeLists.txt;"
					Outputs="osgWidget.vcproj.cmake"/>
				</FileConfiguration>
			</File>
		<Filter
			Name="Source Files"
			Filter="">
			<File
				RelativePath="$(GG_UTILITIES)\OSG_SVN\OpenSceneGraph\src\osgWidget\Box.cpp">
			</File>
			<File
				RelativePath="$(GG_UTILITIES)\OSG_SVN\OpenSceneGraph\src\osgWidget\Browser.cpp">
			</File>
			<File
				RelativePath="$(GG_UTILITIES)\OSG_SVN\OpenSceneGraph\src\osgWidget\PdfReader.cpp">
			</File>
			<File
				RelativePath="$(GG_UTILITIES)\OSG_SVN\OpenSceneGraph\src\osgWidget\VncClient.cpp">
			</File>
			<File
				RelativePath="$(GG_UTILITIES)\OSG_SVN\OpenSceneGraph\src\osgWidget\Canvas.cpp">
			</File>
			<File
				RelativePath="$(GG_UTILITIES)\OSG_SVN\OpenSceneGraph\src\osgWidget\Frame.cpp">
			</File>
			<File
				RelativePath="$(GG_UTILITIES)\OSG_SVN\OpenSceneGraph\src\osgWidget\Input.cpp">
			</File>
			<File
				RelativePath="$(GG_UTILITIES)\OSG_SVN\OpenSceneGraph\src\osgWidget\Label.cpp">
			</File>
			<File
				RelativePath="$(GG_UTILITIES)\OSG_SVN\OpenSceneGraph\src\osgWidget\Lua.cpp">
			</File>
			<File
				RelativePath="$(GG_UTILITIES)\OSG_SVN\OpenSceneGraph\src\osgWidget\Python.cpp">
			</File>
			<File
				RelativePath="$(GG_UTILITIES)\OSG_SVN\OpenSceneGraph\src\osgWidget\StyleManager.cpp">
			</File>
			<File
				RelativePath="$(GG_UTILITIES)\OSG_SVN\OpenSceneGraph\src\osgWidget\Table.cpp">
			</File>
			<File
				RelativePath="$(GG_UTILITIES)\OSG_SVN\OpenSceneGraph\src\osgWidget\Util.cpp">
			</File>
			<File
				RelativePath="$(GG_UTILITIES)\OSG_SVN\OpenSceneGraph\src\osgWidget\Version.cpp">
			</File>
			<File
				RelativePath="$(GG_UTILITIES)\OSG_SVN\OpenSceneGraph\src\osgWidget\ViewerEventHandlers.cpp">
			</File>
			<File
				RelativePath="$(GG_UTILITIES)\OSG_SVN\OpenSceneGraph\src\osgWidget\Widget.cpp">
			</File>
			<File
				RelativePath="$(GG_UTILITIES)\OSG_SVN\OpenSceneGraph\src\osgWidget\Window.cpp">
			</File>
			<File
				RelativePath="$(GG_UTILITIES)\OSG_SVN\OpenSceneGraph\src\osgWidget\WindowManager.cpp">
			</File>
			<File
				RelativePath="$(GG_UTILITIES)\OSG_SVN\OSG_10297_VS_2008\PlatformSpecifics\Windows\OpenSceneGraphVersionInfo.rc">
			</File>
		</Filter>
		<Filter
			Name="Header Files"
			Filter="">
			<File
				RelativePath="$(GG_UTILITIES)\OSG_SVN\OpenSceneGraph\include\osgWidget\Export">
			</File>
			<File
				RelativePath="$(GG_UTILITIES)\OSG_SVN\OpenSceneGraph\include\osgWidget\Box">
			</File>
			<File
				RelativePath="$(GG_UTILITIES)\OSG_SVN\OpenSceneGraph\include\osgWidget\Browser">
			</File>
			<File
				RelativePath="$(GG_UTILITIES)\OSG_SVN\OpenSceneGraph\include\osgWidget\PdfReader">
			</File>
			<File
				RelativePath="$(GG_UTILITIES)\OSG_SVN\OpenSceneGraph\include\osgWidget\VncClient">
			</File>
			<File
				RelativePath="$(GG_UTILITIES)\OSG_SVN\OpenSceneGraph\include\osgWidget\Canvas">
			</File>
			<File
				RelativePath="$(GG_UTILITIES)\OSG_SVN\OpenSceneGraph\include\osgWidget\EventInterface">
			</File>
			<File
				RelativePath="$(GG_UTILITIES)\OSG_SVN\OpenSceneGraph\include\osgWidget\Frame">
			</File>
			<File
				RelativePath="$(GG_UTILITIES)\OSG_SVN\OpenSceneGraph\include\osgWidget\Input">
			</File>
			<File
				RelativePath="$(GG_UTILITIES)\OSG_SVN\OpenSceneGraph\include\osgWidget\Label">
			</File>
			<File
				RelativePath="$(GG_UTILITIES)\OSG_SVN\OpenSceneGraph\include\osgWidget\Lua">
			</File>
			<File
				RelativePath="$(GG_UTILITIES)\OSG_SVN\OpenSceneGraph\include\osgWidget\Python">
			</File>
			<File
				RelativePath="$(GG_UTILITIES)\OSG_SVN\OpenSceneGraph\include\osgWidget\ScriptEngine">
			</File>
			<File
				RelativePath="$(GG_UTILITIES)\OSG_SVN\OpenSceneGraph\include\osgWidget\StyleInterface">
			</File>
			<File
				RelativePath="$(GG_UTILITIES)\OSG_SVN\OpenSceneGraph\include\osgWidget\StyleManager">
			</File>
			<File
				RelativePath="$(GG_UTILITIES)\OSG_SVN\OpenSceneGraph\include\osgWidget\Table">
			</File>
			<File
				RelativePath="$(GG_UTILITIES)\OSG_SVN\OpenSceneGraph\include\osgWidget\Types">
			</File>
			<File
				RelativePath="$(GG_UTILITIES)\OSG_SVN\OpenSceneGraph\include\osgWidget\UIObjectParent">
			</File>
			<File
				RelativePath="$(GG_UTILITIES)\OSG_SVN\OpenSceneGraph\include\osgWidget\Util">
			</File>
			<File
				RelativePath="$(GG_UTILITIES)\OSG_SVN\OpenSceneGraph\include\osgWidget\Version">
			</File>
			<File
				RelativePath="$(GG_UTILITIES)\OSG_SVN\OpenSceneGraph\include\osgWidget\ViewerEventHandlers">
			</File>
			<File
				RelativePath="$(GG_UTILITIES)\OSG_SVN\OpenSceneGraph\include\osgWidget\Widget">
			</File>
			<File
				RelativePath="$(GG_UTILITIES)\OSG_SVN\OpenSceneGraph\include\osgWidget\Window">
			</File>
			<File
				RelativePath="$(GG_UTILITIES)\OSG_SVN\OpenSceneGraph\include\osgWidget\WindowManager">
			</File>
		</Filter>
	</Files>
	<Globals>
	</Globals>
</VisualStudioProject>
